name: gestion_productos
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo


environment:
  sdk: ^3.6.0
  
dependencies:
  mysql1: ^0.20.0
  dart_console: ^4.1.1
  intl: ^0.19.0 # Bajé la versión de intl para que sea compatible con dart_console
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1 # Actualicé la versión de lints
  test: ^1.25.14 # Actualicé la versión de test